# If you come across an error "Filename is too long"
# Then execute this command "git config --global core.longpaths true"
# reference: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - install
  - test
  - build

install_dependencies:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm run runHeadless

build:
  stage: build
  script:
    - npm run build