# If you come across an error "Filename is too long"
# Then execute this command "git config --global core.longpaths true"
# reference: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
image: node:latest


stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm run runHeadless

