# If you come across an error "Filename is too long"
# Then execute this command "git config --global core.longpaths true"
# reference: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
image: node:latest


stages:
  - build
  - test

build:
  stage: build
  image: node:latest
  only:
    - master
  script:
    - npm install -g @angular/cli@10.1.4
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 2 hours
  cache:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run runHeadless

