cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

stages:
  - setup
  - test

build:
  stage: build
  script: 
    - npm run build

setup:
  stage: setup
  script:
    - npm install

test:
  stage: test
  script:
    - ./node_modules/.bin/cypress run
